# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from opentelematicsapi.api_helper import APIHelper


class UseCaseComplianceAndSafetyMonitoringControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(UseCaseComplianceAndSafetyMonitoringControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.use_case_compliance_and_safety_monitoring

    # Clients can request all driver performance summaries for a specific driver within a given period of time.
    #
    #**Access Controls**
    #
    #|Role:  |Vehicle Query|Vehicle Follow|Driver Query|Driver Follow|Driver Dispatch|Driver Duty |HR          |Admin       |
    #|-------|-------------|--------------|------------|-------------|---------------|------------|------------|------------|
    #|Access:| **DENY**    | **DENY**     | **DENY**   | **DENY**    | **DENY**      | **DENY**   | ALLOW      | ALLOW      |
    def test_get_driver_performance_summaries_1(self):
        # Parameters for the API call
        driver_id = '63A9F0EA7BB98050796B649E85481845'
        start_time = '2019-04-05T02:04:16Z'
        stop_time = '2019-04-05T02:04:16Z'

        # Perform the API call through the SDK function
        result = self.controller.get_driver_performance_summaries(driver_id, start_time, stop_time)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))

        
        # Test whether the captured response is as we expected
        self.assertIsNotNone(result)
        self.assertEqual('{  "performanceSummaries": [    {      "id": "C4CA4238A0B923820DCC509A6F75849B",      "providerId": "api.provider.com",      "serverTime": "2019-04-05T02:04:16Z",      "eventStart": "2019-04-05T02:04:16Z",      "eventEnd": "2019-04-05T02:04:16Z",      "driverId": "63A9F0EA7BB98050796B649E85481845",      "distance": 0,      "fuel": 0,      "cruiseTime": 0,      "engineLoadPercent": 0,      "overRpmTime": 0,      "brakeEvents": 0    }  ]}', self.response_catcher.response.raw_body)


