# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class CreateAVehicleRouteResponse(object):

    """Implementation of the 'Create a Vehicle Route response' model.

    TODO: type model description here.

    Attributes:
        route_id (string): the id of the route created, to be used for later
            updates to the route
        stop_id (string): the id of the stop in the created route (most likely
            a re-used location), to be use for later updates to Stop Geograhic
            Details

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "route_id":'routeId',
        "stop_id":'stopId'
    }

    def __init__(self,
                 route_id=None,
                 stop_id=None):
        """Constructor for the CreateAVehicleRouteResponse class"""

        # Initialize members of the class
        self.route_id = route_id
        self.stop_id = stop_id


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        route_id = dictionary.get('routeId')
        stop_id = dictionary.get('stopId')

        # Return an object of this model
        return cls(route_id,
                   stop_id)


