# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ExternallyTriggeredDutyStatusChange(object):

    """Implementation of the 'Externally Triggered Duty Status Change' model.

    TODO: type model description here.

    Attributes:
        date_time (string): Date and time for this status change
        location (string): An object with the location information for this
            status change.
        status (StatusEnum): The status changed-to in this status change

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "date_time":'dateTime',
        "location":'location',
        "status":'status'
    }

    def __init__(self,
                 date_time=None,
                 location=None,
                 status=None):
        """Constructor for the ExternallyTriggeredDutyStatusChange class"""

        # Initialize members of the class
        self.date_time = date_time
        self.location = location
        self.status = status


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        date_time = dictionary.get('dateTime')
        location = dictionary.get('location')
        status = dictionary.get('status')

        # Return an object of this model
        return cls(date_time,
                   location,
                   status)


