# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import opentelematicsapi.models.feed

class FollowFleetVehicleInfoResponse(object):

    """Implementation of the 'Follow Fleet Vehicle Info response' model.

    TODO: type model description here.

    Attributes:
        token (string): a since-token, pass-in the token previously returned
            by GET of `feed` to 'follow' new Log Events
        feed (Feed): the 'feed' of Fleet Vehicle Info

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "token":'token',
        "feed":'feed'
    }

    def __init__(self,
                 token=None,
                 feed=None):
        """Constructor for the FollowFleetVehicleInfoResponse class"""

        # Initialize members of the class
        self.token = token
        self.feed = feed


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        token = dictionary.get('token')
        feed = opentelematicsapi.models.feed.Feed.from_dictionary(dictionary.get('feed')) if dictionary.get('feed') else None

        # Return an object of this model
        return cls(token,
                   feed)


