# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class GPSQualityEnum(object):

    """Implementation of the 'GPS Quality' enum.

    TODO: type enum description here.

    Attributes:
        GPSQUALITY_FINELOCK: gps receiver had fine lock
        GPSQUALITY_OTHER: gps receiver had fix other than fine lock

    """

    GPSQUALITY_FINELOCK = 'GPSQUALITY_FINELOCK'

    GPSQUALITY_OTHER = 'GPSQUALITY_OTHER'

