# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class ServiceStatusEnum(object):

    """Implementation of the 'serviceStatus' enum.

    the current status of the service

    Attributes:
        SERVICESTATUS_OPERATIONAL: the service is operational
        SERVICESTATUS_DEGRADED_PERFORMANCE: the service is operating, but with
            limitations
        SERVICESTATUS_PARTIAL_OUTAGE: there are aspects of the service which
            are not presently available
        SERVICESTATUS_MAJOR_OUTAGE: the service is unavailable

    """

    SERVICESTATUS_OPERATIONAL = 'SERVICESTATUS_OPERATIONAL'

    SERVICESTATUS_DEGRADED_PERFORMANCE = 'SERVICESTATUS_DEGRADED_PERFORMANCE'

    SERVICESTATUS_PARTIAL_OUTAGE = 'SERVICESTATUS_PARTIAL_OUTAGE'

    SERVICESTATUS_MAJOR_OUTAGE = 'SERVICESTATUS_MAJOR_OUTAGE'

