# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class StateOfHealth(object):

    """Implementation of the 'State of Health' model.

    TODO: type model description here.

    Attributes:
        service_status (ServiceStatusEnum): the current status of the service
        date_time (string): Date and time of this service status (this is
            'serverTime')
        factors (list of string): a list of contributing factors to the
            current service status. Providers may use this to communicate
            details about loss of service

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "service_status":'serviceStatus',
        "date_time":'dateTime',
        "factors":'factors'
    }

    def __init__(self,
                 service_status=None,
                 date_time=None,
                 factors=None):
        """Constructor for the StateOfHealth class"""

        # Initialize members of the class
        self.service_status = service_status
        self.date_time = date_time
        self.factors = factors


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        service_status = dictionary.get('serviceStatus')
        date_time = dictionary.get('dateTime')
        factors = dictionary.get('factors')

        # Return an object of this model
        return cls(service_status,
                   date_time,
                   factors)


