# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class StatusEnum(object):

    """Implementation of the 'status' enum.

    The status changed-to in this status change

    Attributes:
        EXTTRIG_STATUS_ON: The driver has changed status to on-duty
        EXTTRIG_STATUS_OFF: The driver has changed status to off-duty

    """

    EXTTRIG_STATUS_ON = 'EXTTRIG_STATUS_ON'

    EXTTRIG_STATUS_OFF = 'EXTTRIG_STATUS_OFF'

