# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class StateEnum(object):

    """Implementation of the 'state' enum.

    The State of the Log Event record.

    Attributes:
        STATE_ACTIVE: The log is active and has been accepted by the driver.
        STATE_INACTIVE: The log is inactive. It has been removed or it is the
            modification history of a log.
        STATE_REJECTED: The log is a rejected edit request from another user.
        STATE_REQUESTED: The log is a pending edit request from another user.

    """

    STATE_ACTIVE = 'STATE_ACTIVE'

    STATE_INACTIVE = 'STATE_INACTIVE'

    STATE_REJECTED = 'STATE_REJECTED'

    STATE_REQUESTED = 'STATE_REQUESTED'

