# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class TriggerEnum(object):

    """Implementation of the 'trigger' enum.

    type flagged event

    Attributes:
        FLAGGEDTYPE_ROLL_STABILITY: Roll stability flagged event
        FLAGGEDTYPE_SUDDEN_START: Sudden start flagged event
        FLAGGEDTYPE_SUDDEN_STOP: Sudden stop flagged event
        FLAGGEDTYPE_COLLISION: Collision flagged event
        FLAGGEDTYPE_ONBOARD_RECORDING: onboard recording flagged event

    """

    FLAGGEDTYPE_ROLL_STABILITY = 'FLAGGEDTYPE_ROLL_STABILITY'

    FLAGGEDTYPE_SUDDEN_START = 'FLAGGEDTYPE_SUDDEN_START'

    FLAGGEDTYPE_SUDDEN_STOP = 'FLAGGEDTYPE_SUDDEN_STOP'

    FLAGGEDTYPE_COLLISION = 'FLAGGEDTYPE_COLLISION'

    FLAGGEDTYPE_ONBOARD_RECORDING = 'FLAGGEDTYPE_ONBOARD_RECORDING'

