# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class UpdateStopGeographicDetailsResponse(object):

    """Implementation of the 'Update Stop Geographic Details response' model.

    TODO: type model description here.

    Attributes:
        stop_id (string): the id of the stop that was updated, to be used for
            later updates to Stop Geograhic Details

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "stop_id":'stopId'
    }

    def __init__(self,
                 stop_id=None):
        """Constructor for the UpdateStopGeographicDetailsResponse class"""

        # Initialize members of the class
        self.stop_id = stop_id


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        stop_id = dictionary.get('stopId')

        # Return an object of this model
        return cls(stop_id)


