# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class VehicleLocationTime(object):

    """Implementation of the 'Vehicle Location Time' model.

    TODO: type model description here.

    Attributes:
        id (string): The unique identifier for the specific Entity object in
            the system.
        provider_id (string): The unique 'Provider ID' of the TSP.
        server_time (string): Date and time when this object was received at
            the TSP
        vehicle_id (string): The vehicle id associated with this Location
            Time
        date_time (string): time
        location (string): location

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id":'id',
        "provider_id":'providerId',
        "server_time":'serverTime',
        "vehicle_id":'vehicleId',
        "date_time":'dateTime',
        "location":'location'
    }

    def __init__(self,
                 id=None,
                 provider_id=None,
                 server_time=None,
                 vehicle_id=None,
                 date_time=None,
                 location=None):
        """Constructor for the VehicleLocationTime class"""

        # Initialize members of the class
        self.id = id
        self.provider_id = provider_id
        self.server_time = server_time
        self.vehicle_id = vehicle_id
        self.date_time = date_time
        self.location = location


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        provider_id = dictionary.get('providerId')
        server_time = dictionary.get('serverTime')
        vehicle_id = dictionary.get('vehicleId')
        date_time = dictionary.get('dateTime')
        location = dictionary.get('location')

        # Return an object of this model
        return cls(id,
                   provider_id,
                   server_time,
                   vehicle_id,
                   date_time,
                   location)


