# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import opentelematicsapi.models.state_of_health

class CheckPast30dStateOfHealthResponse(object):

    """Implementation of the 'Check Past 30d State of Health response' model.

    TODO: type model description here.

    Attributes:
        data (list of StateOfHealth): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "data":'data'
    }

    def __init__(self,
                 data=None):
        """Constructor for the CheckPast30dStateOfHealthResponse class"""

        # Initialize members of the class
        self.data = data


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        data = None
        if dictionary.get('data') != None:
            data = list()
            for structure in dictionary.get('data'):
                data.append(opentelematicsapi.models.state_of_health.StateOfHealth.from_dictionary(structure))

        # Return an object of this model
        return cls(data)


