# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class ClearTypeEnum(object):

    """Implementation of the 'clearType' enum.

    by what means was this fault cleared

    Attributes:
        CLEARTYPE_BYSYSTEMS: cleared by systems
        CLEARTYPE_MANUALLYBACKOFFICE: cleared manually in backoffice

    """

    CLEARTYPE_BYSYSTEMS = 'CLEARTYPE_BYSYSTEMS'

    CLEARTYPE_MANUALLYBACKOFFICE = 'CLEARTYPE_MANUALLYBACKOFFICE'

