# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ExternalTSPPortalUserManagement(object):

    """Implementation of the 'External TSP Portal User Management' model.

    TODO: type model description here.

    Attributes:
        username (string): TSP portal username
        password (string): user password
        enabled (bool): this user is enabled or disabled

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "username":'username',
        "password":'password',
        "enabled":'enabled'
    }

    def __init__(self,
                 username=None,
                 password=None,
                 enabled=None):
        """Constructor for the ExternalTSPPortalUserManagement class"""

        # Initialize members of the class
        self.username = username
        self.password = password
        self.enabled = enabled


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        username = dictionary.get('username')
        password = dictionary.get('password')
        enabled = dictionary.get('enabled')

        # Return an object of this model
        return cls(username,
                   password,
                   enabled)


