# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ExternallySourcedVehicleDisplayMessages(object):

    """Implementation of the 'Externally Sourced Vehicle Display Messages' model.

    TODO: type model description here.

    Attributes:
        subject (string): a brief 'subject-line' for this message
        message (string): the message to be displayed to the driver

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "message":'message',
        "subject":'subject'
    }

    def __init__(self,
                 message=None,
                 subject=None):
        """Constructor for the ExternallySourcedVehicleDisplayMessages class"""

        # Initialize members of the class
        self.subject = subject
        self.message = message


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        message = dictionary.get('message')
        subject = dictionary.get('subject')

        # Return an object of this model
        return cls(message,
                   subject)


