# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class OriginEnum(object):

    """Implementation of the 'origin' enum.

    The Origin from where this log originated.

    Attributes:
        ORIGIN_AUTOMATIC: Automatic recorded by device
        ORIGIN_MANUAL: Manual entry by driver.
        ORIGIN_OTHERUSER: Other authenticated user.
        ORIGIN_UNASSIGNED: Unassigned driver.

    """

    ORIGIN_AUTOMATIC = 'ORIGIN_AUTOMATIC'

    ORIGIN_MANUAL = 'ORIGIN_MANUAL'

    ORIGIN_OTHERUSER = 'ORIGIN_OTHERUSER'

    ORIGIN_UNASSIGNED = 'ORIGIN_UNASSIGNED'

