# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class ParameterOrSubsystemIdTypeEnum(object):

    """Implementation of the 'parameterOrSubsystemIdType' enum.

    does *faultCodeParameterorSubsystemId* encode a PID or SID as defined in
    SAE J1587?

    Attributes:
        PIDORSID_PID: This is a PID
        PIDORSID_SID: This is a SID

    """

    PIDORSID_PID = 'PIDORSID_PID'

    PIDORSID_SID = 'PIDORSID_SID'

