# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class ParticulateFilterStatusEnum(object):

    """Implementation of the 'particulateFilterStatus' enum.

    the regen status at the end of this event

    Attributes:
        ENUM_FILTERSTATUS_REGEN_NEEDED: Filter regen needed
        ENUM_FILTERSTATUS_FORCED_REGEN_WILL_HAPPEN: Filter forced regen will
            happen
        ENUM_FILTERSTATUS_ACTIVE_REGEN_START: Filter active regen started
        ENUM_FILTERSTATUS_PASSIVE_REGEN_START: Filter passive regen started
        ENUM_FILTERSTATUS_ACTIVE_REGEN_END: Filter active regen ended
        ENUM_FILTERSTATUS_PASSIVE_REGEN_END: Filter passive regen ended

    """

    ENUM_FILTERSTATUS_REGEN_NEEDED = '`FILTERSTATUS_REGEN_NEEDED\''

    ENUM_FILTERSTATUS_FORCED_REGEN_WILL_HAPPEN = '`FILTERSTATUS_FORCED_REGEN_WILL_HAPPEN\''

    ENUM_FILTERSTATUS_ACTIVE_REGEN_START = '`FILTERSTATUS_ACTIVE_REGEN_START\''

    ENUM_FILTERSTATUS_PASSIVE_REGEN_START = '`FILTERSTATUS_PASSIVE_REGEN_START\''

    ENUM_FILTERSTATUS_ACTIVE_REGEN_END = '`FILTERSTATUS_ACTIVE_REGEN_END\''

    ENUM_FILTERSTATUS_PASSIVE_REGEN_END = '`FILTERSTATUS_PASSIVE_REGEN_END\''

