# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class RegionSpecificWaivers(object):

    """Implementation of the 'Region Specific Waivers' model.

    TODO: type model description here.

    Attributes:
        id (string): The unique identifier for the specific Entity object in
            the system.
        provider_id (string): The unique 'Provider ID' of the TSP
        server_time (string): Date and time when this object was received at
            the TSP
        driver_id (string): The id of the driver with the region specific
            waiver.
        country (string): short code for the country of the region dictating
            the specific waiver
        region (string): short code for the country's
            region/state/province/territory dictating the specific waiver
        waiver_day (string): The date of the effect of the waiver -- time is
            ignored

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id":'id',
        "provider_id":'providerId',
        "server_time":'serverTime',
        "driver_id":'driverId',
        "waiver_day":'waiverDay',
        "country":'country',
        "region":'region'
    }

    def __init__(self,
                 id=None,
                 provider_id=None,
                 server_time=None,
                 driver_id=None,
                 waiver_day=None,
                 country=None,
                 region=None):
        """Constructor for the RegionSpecificWaivers class"""

        # Initialize members of the class
        self.id = id
        self.provider_id = provider_id
        self.server_time = server_time
        self.driver_id = driver_id
        self.country = country
        self.region = region
        self.waiver_day = waiver_day


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        provider_id = dictionary.get('providerId')
        server_time = dictionary.get('serverTime')
        driver_id = dictionary.get('driverId')
        waiver_day = dictionary.get('waiverDay')
        country = dictionary.get('country')
        region = dictionary.get('region')

        # Return an object of this model
        return cls(id,
                   provider_id,
                   server_time,
                   driver_id,
                   waiver_day,
                   country,
                   region)


