# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class TimeResolutionEnum(object):

    """Implementation of the 'timeResolution' enum.

    a status variable to indicate if this time history has a higher available
    resolution at the TSP

    Attributes:
        TIMERESOLUTION_MAX: This is at the highest available time resolution
        TIMERESOLUTION_NOT_MAX: This is not at the highest available time
            resolution

    """

    TIMERESOLUTION_MAX = 'TIMERESOLUTION_MAX'

    TIMERESOLUTION_NOT_MAX = 'TIMERESOLUTION_NOT_MAX'

