# -*- coding: utf-8 -*-

"""
    opentelematicsapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import opentelematicsapi.models.vehicle_location_time

class VehicleLocationTimeHistory(object):

    """Implementation of the 'Vehicle Location Time History' model.

    TODO: type model description here.

    Attributes:
        data (list of VehicleLocationTime): array of Location Times
            representing the vehicle's location over time.
        time_resolution (TimeResolutionEnum): a status variable to indicate if
            this time history has a higher available resolution at the TSP

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "data":'data',
        "time_resolution":'timeResolution'
    }

    def __init__(self,
                 data=None,
                 time_resolution=None):
        """Constructor for the VehicleLocationTimeHistory class"""

        # Initialize members of the class
        self.data = data
        self.time_resolution = time_resolution


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        data = None
        if dictionary.get('data') != None:
            data = list()
            for structure in dictionary.get('data'):
                data.append(opentelematicsapi.models.vehicle_location_time.VehicleLocationTime.from_dictionary(structure))
        time_resolution = dictionary.get('timeResolution')

        # Return an object of this model
        return cls(data,
                   time_resolution)


