CREATE TABLE [dbo].[VehicleFaultCodeEvent]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [vehicleId] UNIQUEIDENTIFIER NULL, 
    [longitutude] NUMERIC(18, 8) NULL, 
    [latitude] NUMERIC(18, 8) NULL, 
    [eventComment] NVARCHAR(500) NULL, 
    [triggerDate] DATETIMEOFFSET NULL, 
    [clearedDate] DATETIMEOFFSET NULL, 
    [occurences] INT NULL, 
    [messageIdentifier] INT NULL, 
    [parameterOrSubsystemsIdType] NVARCHAR(50) NULL, 
    [faultCodeParameterOfSubsystemId] INT NULL, 
    [sourceAddress] INT NULL, 
    [suspectParamterNumber] INT NULL, 
    [failureModeIdentifier] INT NULL, 
    [urgentFlag] BIT NULL, 
    [odometer] INT NULL, 
    [engineRpm] INT NULL, 
    [ecmSpeed] INT NULL, 
    [ccSwitch] BIT NULL, 
    [ccSetSwitch] BIT NULL, 
    [ccCoastSwitch] BIT NULL, 
    [ccClutchSwitch] BIT NULL, 
    [ccCruiseSwitch] BIT NULL, 
    [ccResumeSwitch] BIT NULL, 
    [ccAccelerationSwitch] BIT NULL, 
    [ccBrakeSwitch] BIT NULL, 
    [ccSpeed] INT NULL, 
    [ignitionAccessory] BIT NULL, 
    [ignitionRunContact] BIT NULL, 
    [ignitionCrankContact] BIT NULL, 
    [ignitionAidContact] BIT NULL, 
    [gpsQuality] NVARCHAR(50) NULL, 
    [clearType] NVARCHAR(50) NULL, 
    CONSTRAINT [FK_VehicleFaultCodeEvent_Vehicle] FOREIGN KEY ([VehicleId]) REFERENCES [Vehicle]([Id])
)
