CREATE TABLE [dbo].[VehiclePerformanceEvent]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newid(), 
    [eventStart] DATETIMEOFFSET NOT NULL, 
    [eventEnd] DATETIMEOFFSET NOT NULL, 
    [vehicleId] UNIQUEIDENTIFIER NOT NULL, 
    [eventComment] NVARCHAR(1000) NULL, 
    [hours] INT NOT NULL, 
    [performanceThresholdId] UNIQUEIDENTIFIER NOT NULL, 
    [odometerStart] INT NOT NULL, 
    [odometerEnd] INT NOT NULL, 
    [engineTime] INT NOT NULL, 
    [movingTime] INT NOT NULL, 
    [startFuel] INT NOT NULL, 
    [endFuel] INT NOT NULL, 
    [brakeApplications] INT NOT NULL, 
    [engineLoadStopped] NUMERIC(3, 2) NOT NULL, 
    [engineLoadMoving] NUMERIC(3, 2) NOT NULL, 
    [headlightTime] INT NOT NULL, 
    [speedGovernorValue] INT NOT NULL, 
    [overRpmTime] INT NULL, 
    [overSpeedTime] INT NULL, 
    [excessSpeedTime] INT NULL, 
    [longIdleTime] INT NULL, 
    [shortIdleTime] INT NULL, 
    [shortIdleCount] INT NULL, 
    [longIdleFuel] INT NULL, 
    [shortIdleFuel] INT NULL, 
    [cruiseEvents] INT NULL, 
    [cruiseTime] INT NULL, 
    [cruiseFuel] INT NULL, 
    [cruiseDistance] INT NULL, 
    [topGearValue] INT NULL, 
    [topGearTime] INT NULL, 
    [topGearFuel] INT NULL, 
    [topGearDistance] INT NULL, 
    [ptoFuel] INT NULL, 
    [ptoTime] INT NULL, 
    [seatBeltTime] INT NULL, 
    [particulateFilterStatus] NVARCHAR(50) NULL, 
    [exhaustFluidLevel] INT NULL, 
    [overspeedLowThrottle] BIT NULL, 
    [overspeedHiThrottle] BIT NULL, 
    [overrpmLowThrottle] BIT NULL, 
    [overrpmHiThrottle] BIT NULL, 
    [lkaDisable] BIT NULL, 
    [ldwActive] BIT NULL, 
    [ldwDisable] BIT NULL, 
    [lkaActive] BIT NULL, 
    CONSTRAINT [FK_VehiclePerformanceEvent_VechiclePerformanceThreshold] FOREIGN KEY ([performanceThresholdId]) REFERENCES [VehiclePerformanceThreshold]([Id]), 
    CONSTRAINT [FK_VehiclePerformanceEvent_Vehicle] FOREIGN KEY ([vehicleId]) REFERENCES [Vehicle]([Id]) 
)
