CREATE TABLE [dbo].[VehiclePerformanceEvent]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [providerId] UNIQUEIDENTIFIER NULL, 
    [eventStart] DATETIMEOFFSET NULL, 
    [eventEnd] DATETIMEOFFSET NULL, 
    [vehicleId] UNIQUEIDENTIFIER NULL, 
    [eventComment] NVARCHAR(1000) NULL, 
    [hours] NUMERIC(5, 2) NULL, 
    [thresholdId] UNIQUEIDENTIFIER NULL, 
    [odometerStart] NUMERIC(7, 2) NULL, 
    [odometerEnd] NUMERIC(7, 2) NULL, 
    [engineTime] INT NULL, 
    [movingTime] INT NULL, 
    [startFuel] NUMERIC(3, 2) NULL, 
    [endFuel] NUMERIC(3, 2) NULL, 
    [brakeApplications] INT NULL, 
    [engineLoadStopped] NUMERIC(3, 2) NULL, 
    [engineLoadMoving] NUMERIC(3, 2) NULL, 
    [headlightTime] INT NULL, 
    [speedGovernorValue] NUMERIC(5, 2) NULL, 
    [overRpmTime] INT NULL, 
    [overSpeedTime] INT NULL, 
    [longIdleTiime] INT NULL, 
    [shortIdleTiime] INT NULL, 
    [shortIdleCount] INT NULL, 
    [longIdelFuel] NUMERIC(5, 2) NULL, 
    [shortIdleFuel] NUMERIC(5, 2) NULL, 
    [cruiseEvents] INT NULL, 
    [cruiseTime] INT NULL, 
    [cruiseDistance] INT NULL, 
    [topGearValue] INT NULL, 
    [topGearTime] INT NULL, 
    [topGearFuel] NUMERIC(5, 2) NULL, 
    [topGearDistance] INT NULL, 
    [ptoFuel] NUMERIC(5, 2) NULL, 
    [ptoTime] INT NULL, 
    [seatBeltTime] INT NULL, 
    [particleFilterStatus] NVARCHAR(50) NULL, 
    [exhaustFluidLevel] NUMERIC(5, 2) NULL, 
    [overspeedLowThrottle] BIT NULL, 
    [overspeedHiThrottle] BIT NULL, 
    [overrpmLowThrottle] BIT NULL, 
    [overrpmHiThrottle] BIT NULL
)
