CREATE TABLE [dbo].[VehiclePerformanceEvent]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [eventStart] DATETIMEOFFSET NULL, 
    [eventEnd] DATETIMEOFFSET NULL, 
    [vehicleId] UNIQUEIDENTIFIER NULL, 
    [eventComment] NVARCHAR(1000) NULL, 
    [hours] INT NULL, 
    [performanceThresholdId] UNIQUEIDENTIFIER NULL, 
    [odometerStart] INT NULL, 
    [odometerEnd] INT NULL, 
    [engineTime] INT NULL, 
    [movingTime] INT NULL, 
    [startFuel] INT NULL, 
    [endFuel] INT NULL, 
    [brakeApplications] INT NULL, 
    [engineLoadStopped] NUMERIC(3, 2) NULL, 
    [engineLoadMoving] NUMERIC(3, 2) NULL, 
    [headlightTime] INT NULL, 
    [speedGovernorValue] INT NULL, 
    [overRpmTime] INT NULL, 
    [overSpeedTime] INT NULL, 
    [excessSpeedTime] INT NULL, 
    [longIdleTime] INT NULL, 
    [shortIdleTime] INT NULL, 
    [shortIdleCount] INT NULL, 
    [longIdleFuel] INT NULL, 
    [shortIdleFuel] INT NULL, 
    [cruiseEvents] INT NULL, 
    [cruiseTime] INT NULL, 
    [cuiseFuel] INT NULL, 
    [cruiseDistance] INT NULL, 
    [topGearValue] INT NULL, 
    [topGearTime] INT NULL, 
    [topGearFuel] INT NULL, 
    [topGearDistance] INT NULL, 
    [ptoFuel] INT NULL, 
    [ptoTime] INT NULL, 
    [seatBeltTime] INT NULL, 
    [particulateFilterStatus] NVARCHAR(50) NULL, 
    [exhaustFluidLevel] INT NULL, 
    [overspeedLowThrottle] BIT NULL, 
    [overspeedHiThrottle] BIT NULL, 
    [overrpmLowThrottle] BIT NULL, 
    [overrpmHiThrottle] BIT NULL, 
    CONSTRAINT [FK_VehiclePerformanceEvent_VechiclePerformanceThreshold] FOREIGN KEY ([PerformanceThresholdId]) REFERENCES [VehiclePerformanceThreshold]([Id]), 
    CONSTRAINT [FK_VehiclePerformanceEvent_Vehicle] FOREIGN KEY ([VehicleId]) REFERENCES [Vehicle]([Id]) 
)
