CREATE TABLE [dbo].[VehicleFlaggedEvent]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newid(), 
    [eventStart] DATETIMEOFFSET NOT NULL, 
    [eventEnd] DATETIMEOFFSET NOT NULL, 
    [vehicleId] UNIQUEIDENTIFIER NOT NULL, 
	[driverId] UNIQUEIDENTIFIER NULL, 
    [eventComment] NVARCHAR(1000) NULL, 
    [trigger] NVARCHAR(100) NOT NULL, 
    [gpsSpeed] NUMERIC(18, 5) NULL, 
    [gpsHeading] NUMERIC(18, 5) NULL, 
    [gpsQuality] NVARCHAR(50) NULL, 
    [ecmSpeed] NUMERIC(18, 5) NOT NULL, 
    [engineRPM] NUMERIC(18, 5) NOT NULL, 
    [accelerationPercent] NUMERIC(18, 5) NOT NULL, 
    [seatBelts] BIT NULL, 
    [cruiseStatus] NVARCHAR(MAX) NULL, 
    [parkingBreak] BIT NOT NULL, 
    [ignitionStatus] NVARCHAR(MAX) NOT NULL, 
    [forwardVehicleSpeed] NUMERIC(18, 5) NOT NULL, 
    [forwardVehicleDistance] NUMERIC(18, 5) NOT NULL, 
    [forwardVehicleElapsed] NUMERIC(18, 5) NOT NULL, 
    [odometer] INT NOT NULL, 
    CONSTRAINT [FK_VehicleFlaggedEvent_Vehicle] FOREIGN KEY ([vehicleId]) REFERENCES [Vehicle]([Id])
)
