using System;
using System.Collections.Generic;
using System.Text;
using Prototype.OpenTelematics.DataAccess;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Prototype.OpenTelematics.Models;
//
//    var breakRulesAndWaivers = BreakRulesAndWaivers.FromJson(jsonString);

namespace Prototype.OpenTelematics.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BreakRulesAndWaivers
    {
        /// <summary>
        /// the Region Specific Breaks Rules for this driver for the requested time period
        /// </summary>
        public DriverBreakRule[] BreakRules { get; set; }

        /// <summary>
        /// the Region Specific Waivers for this driver for the requested time period
        /// </summary>
        public DriverWaiver[] Waivers { get; set; }
    }
}
